export const FEATURE_CODES = [
  'multiTeacherStudent',
  'teacherRosterGroups',
  'teacherBulkOps',
  'teacherAssistants',
  'teacherRegsPayments',
  'teacherSubscriptions',
  'examWorkflows',
  'platformCatalog',
  'platformSyndication',
  'liveSessionsCore',
  'liveSessionsChat',
  'liveSessionsPolls',
  'discussions',
  'reviews',
  'notificationsUnified',
  'badges',
  'adminApprovals',
  'adminModeration',
  'adminOps',
  'reportsTeacher',
  'reportsStudent',
  'analyticsPlatform',
  'offers',
  'publicCoursePreviewEnabled',
  'branding',
  'rtlLtrToggle',
  'assetPlaceholders',
  'aiTeacher',
  'feature.teacher.summarizer',
  'feature.teacher.rewriter',
  'feature.teacher.level-adapter',
  'feature.teacher.question-generator',
  'aiStudent',
  'aiFreeTrial',
  'feature.student.tldr',
  'feature.student.flashcards',
  'feature.student.practice-questions',
  'feature.student.instant-feedback',
  'englishLab',
  'englishLab.animals',
  'englishLab.fruits',
  'englishLab.actions',
  'englishLab.bodyParts',
  'englishLab.emotions'
] as const;

export type FeatureCode = (typeof FEATURE_CODES)[number];

export const FEATURE = {
  multiTeacherStudent: 'multiTeacherStudent',
  teacherRosterGroups: 'teacherRosterGroups',
  teacherBulkOps: 'teacherBulkOps',
  teacherAssistants: 'teacherAssistants',
  teacherRegsPayments: 'teacherRegsPayments',
  teacherSubscriptions: 'teacherSubscriptions',
  examWorkflows: 'examWorkflows',
  platformCatalog: 'platformCatalog',
  platformSyndication: 'platformSyndication',
  liveSessionsCore: 'liveSessionsCore',
  liveSessionsChat: 'liveSessionsChat',
  liveSessionsPolls: 'liveSessionsPolls',
  discussions: 'discussions',
  reviews: 'reviews',
  notificationsUnified: 'notificationsUnified',
  badges: 'badges',
  adminApprovals: 'adminApprovals',
  adminModeration: 'adminModeration',
  adminOps: 'adminOps',
  reportsTeacher: 'reportsTeacher',
  reportsStudent: 'reportsStudent',
  analyticsPlatform: 'analyticsPlatform',
  offers: 'offers',
  publicCoursePreviewEnabled: 'publicCoursePreviewEnabled',
  branding: 'branding',
  rtlLtrToggle: 'rtlLtrToggle',
  assetPlaceholders: 'assetPlaceholders',
  aiTeacher: 'aiTeacher',
  teacherSummarizer: 'feature.teacher.summarizer',
  teacherRewriter: 'feature.teacher.rewriter',
  teacherLevelAdapter: 'feature.teacher.level-adapter',
  teacherQuestionGenerator: 'feature.teacher.question-generator',
  aiStudent: 'aiStudent',
  aiFreeTrial: 'aiFreeTrial',
  studentTldr: 'feature.student.tldr',
  studentFlashcards: 'feature.student.flashcards',
  studentPracticeQuestions: 'feature.student.practice-questions',
  studentInstantFeedback: 'feature.student.instant-feedback',
  englishLab: 'englishLab',
  englishLabAnimals: 'englishLab.animals',
  englishLabFruits: 'englishLab.fruits',
  englishLabActions: 'englishLab.actions',
  englishLabBody: 'englishLab.bodyParts',
  englishLabEmotions: 'englishLab.emotions'
} as const satisfies Record<string, FeatureCode>;

export const ENTITLEMENT_KEYS = [
  'student_limit',
  'course_limit',
  'lesson_video_limit',
  'staff_limit',
  'device_limit',
  'video_storage_hours',
  'video_storage_gb',
  'streaming_minutes_monthly',
  'max_video_resolution',
  'max_video_duration_minutes',
  'video_resolution_policy',
  'video_storage_warning_percent',
  'video_storage_critical_percent',
  'streaming_warning_percent',
  'streaming_critical_percent',
  'video_storage_grace_days',
  'streaming_grace_days'
] as const;

export type EntitlementKey = (typeof ENTITLEMENT_KEYS)[number];

export const ENTITLEMENT: Record<EntitlementKey, EntitlementKey> = {
  student_limit: 'student_limit',
  course_limit: 'course_limit',
  lesson_video_limit: 'lesson_video_limit',
  staff_limit: 'staff_limit',
  device_limit: 'device_limit',
  video_storage_hours: 'video_storage_hours',
  video_storage_gb: 'video_storage_gb',
  streaming_minutes_monthly: 'streaming_minutes_monthly',
  max_video_resolution: 'max_video_resolution',
  max_video_duration_minutes: 'max_video_duration_minutes',
  video_resolution_policy: 'video_resolution_policy',
  video_storage_warning_percent: 'video_storage_warning_percent',
  video_storage_critical_percent: 'video_storage_critical_percent',
  streaming_warning_percent: 'streaming_warning_percent',
  streaming_critical_percent: 'streaming_critical_percent',
  video_storage_grace_days: 'video_storage_grace_days',
  streaming_grace_days: 'streaming_grace_days'
} as const;

export const FEATURE_LABELS = {
  multiTeacherStudent: 'Multi teacher experience',
  teacherRosterGroups: 'Roster groups',
  teacherBulkOps: 'Bulk roster operations',
  teacherAssistants: 'Teacher assistants',
  teacherRegsPayments: 'Teacher registration payments',
  teacherSubscriptions: 'Teacher plan upgrades',
  examWorkflows: 'Exam workflows',
  platformCatalog: 'Platform catalog',
  platformSyndication: 'Platform syndication',
  liveSessionsCore: 'Live sessions core',
  liveSessionsChat: 'Live sessions chat',
  liveSessionsPolls: 'Live sessions polls',
  discussions: 'Discussions',
  reviews: 'Reviews',
  notificationsUnified: 'Unified notifications',
  badges: 'Badges',
  adminApprovals: 'Admin approvals',
  adminModeration: 'Admin moderation',
  adminOps: 'Admin operations',
  reportsTeacher: 'Teacher reports',
  reportsStudent: 'Student reports',
  analyticsPlatform: 'Platform analytics',
  offers: 'Offers',
  publicCoursePreviewEnabled: 'Public course preview',
  branding: 'Branding',
  rtlLtrToggle: 'RTL/LTR toggle',
  assetPlaceholders: 'Asset placeholders',
  aiTeacher: 'AI teacher tools',
  'feature.teacher.summarizer': 'Lesson summarizer',
  'feature.teacher.rewriter': 'Lesson rewriter',
  'feature.teacher.level-adapter': 'Level adapter',
  'feature.teacher.question-generator': 'AI question generator',
  aiStudent: 'AI student helpers',
  aiFreeTrial: 'AI free trial',
  'feature.student.tldr': 'Student TLDR summaries',
  'feature.student.flashcards': 'Student flashcards',
  'feature.student.practice-questions': 'Student practice questions',
  'feature.student.instant-feedback': 'Student instant feedback',
  englishLab: 'Zidni AI English Lab',
  'englishLab.animals': 'English Lab – Animals',
  'englishLab.fruits': 'English Lab – Fruits',
  'englishLab.actions': 'English Lab – Actions',
  'englishLab.bodyParts': 'English Lab – Body Parts',
  'englishLab.emotions': 'English Lab – Emotions'
} as const satisfies Record<FeatureCode, string>;

export const ENTITLEMENT_LABELS: Record<EntitlementKey, string> = {
  student_limit: 'Student limit',
  course_limit: 'Course limit',
  lesson_video_limit: 'Lesson video limit',
  staff_limit: 'Staff limit',
  device_limit: 'Device limit',
  video_storage_hours: 'Video storage (hours)',
  video_storage_gb: 'Video storage size (GB)',
  streaming_minutes_monthly: 'Streaming minutes / month',
  max_video_resolution: 'Max video resolution (p)',
  max_video_duration_minutes: 'Max single video duration (minutes)',
  video_resolution_policy: 'Video resolution policy (block/downscale)',
  video_storage_warning_percent: 'Video storage warning %',
  video_storage_critical_percent: 'Video storage critical %',
  streaming_warning_percent: 'Streaming warning %',
  streaming_critical_percent: 'Streaming critical %',
  video_storage_grace_days: 'Video storage grace days',
  streaming_grace_days: 'Streaming grace days'
};

export function isFeatureCode(value: string | null | undefined): value is FeatureCode {
  return !!value && FEATURE_CODES.includes(value as FeatureCode);
}

export function isEntitlementKey(value: string | null | undefined): value is EntitlementKey {
  return !!value && ENTITLEMENT_KEYS.includes(value as EntitlementKey);
}
